---
title: "conservation areas exploration"
author: "Iris Foxfoot"
date: "2/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(here)
library(tidyverse)
library(janitor)
library(tmap)
```

This is an exploration of the California Conservation Easement Database (CCED) and California Protected Area Database (CPAD). The goal is to find conservation areas that have never been farmed, which are similar enough to compare to agricultural areas

```{r, read in data}
#read in cced database
easements <- read_sf(here("data", "CCED_2021b", "CCED_2021b_Release.shp"))

#read in cpad database
protected_areas_holdings <- read_sf(here("data", "CPAD_2021b", "CPAD_2021b_Holdings.shp"))
protected_areas_superunits <- read_sf(here("data", "CPAD_2021b", "CPAD_2021b_SuperUnits.shp"))
protected_areas_units <- read_sf(here("data", "CPAD_2021b", "CPAD_2021b_Units.shp"))

#getting crs for protected ares
proj_crs <- st_crs(easements)

#read in aggregated agriculture file (years 2016-2019), transform to same crs as other files
farms <- read_sf(here("data", "shapefiles_written", "unioned_fields_20162019", "unioned_fields_20162019.shp")) %>% 
  st_transform(crs = proj_crs)

#read in kern county shapefile
kern_county <- read_sf(here("data", "Kern_County_Boundary")) %>% 
  st_transform(crs = proj_crs)

#read in soil data
soil_quality <- read_sf(here("R_input", "spatial", "SSURGOsoil", "kern_soil.gpkg"))
soil_quality_factX <- read_sf(here("R_input", "spatial", "SSURGOsoil", "kern_soil_factX.gpkg"))
```

```{r}
#get protected areas within 100m of farms

#buffer farms to 100m
farms_buffered <- st_buffer(farms, dist = 100)

easements_kern <- easements %>% 
  filter(st_intersects(geometry, farms_buffered, sparse = FALSE))

holdings_kern <- protected_areas_holdings %>% 
  filter(st_intersects(geometry, farms_buffered, sparse = FALSE))
  
superunits_kern <- protected_areas_superunits %>% 
  filter(st_intersects(geometry, farms_buffered, sparse = FALSE))

units_kern <- protected_areas_units %>% 
  filter(st_intersects(geometry, farms_buffered, sparse = FALSE))

#get gap status 1, 2, 3, or pre 1950s conservation areas
#also make col names consistent

long_easements <- easements_kern %>% 
  filter(gapcat <= 3 | year_est %in% c(1:1950)) %>% 
  clean_names() %>% 
  mutate("unit_id" = e_hold_id,
         "unit_name" =  sitename,
         "agncy_name" = esmthldr,
         "yr_est" =  year_est,
         type = "easement") %>% 
  dplyr::select(type, unit_id, unit_name, agncy_name, yr_est, gap1_acres, gap2_acres, gap3_acres, gap4_acres)

long_holdings <- holdings_kern %>% 
  filter(GAP1_acres > 0 | GAP2_acres > 0 | GAP3_acres > 0 | YR_EST %in% c(1:1950)) %>% 
  clean_names() %>%
  mutate(type = "holding") %>% 
  dplyr::select(type, unit_id, unit_name, agncy_name, yr_est, gap1_acres, gap2_acres, gap3_acres, gap4_acres)

long_superunits <- superunits_kern %>% 
  filter(GAP1_acres > 0 | GAP2_acres > 0 | GAP3_acres > 0 | YR_EST %in% c(1:1950)) %>% 
  clean_names() %>% 
  mutate("unit_id" = suid_nma,
         "unit_name" =  park_name,
         "agncy_name" = mng_agency,
         type = "superunit") %>% 
  dplyr::select(type, unit_id, unit_name, agncy_name, yr_est, gap1_acres, gap2_acres, gap3_acres, gap4_acres)
  
long_units <- units_kern %>% 
  filter(GAP1_acres > 0 | GAP2_acres > 0 | GAP3_acres > 0 | YR_EST %in% c(1:1950))  %>% 
  clean_names() %>%
  mutate(type = "unit") %>% 
  dplyr::select(type, unit_id, unit_name, agncy_name, yr_est, gap1_acres, gap2_acres, gap3_acres, gap4_acres)

#bind together #not including units because they are super big
kern_conservation_areas <- rbind(long_easements, long_holdings)#, long_superunits, long_units)

plot(st_geometry(kern_conservation_areas))


#mutate to include column with gap status #fix this for case when multiple gap status exist
kern_conservation_GAP <- kern_conservation_areas %>% 
  mutate(gap = case_when(gap1_acres > 0 ~ "Gap 1",
                         gap2_acres > 0 ~ "Gap 2",
                         gap3_acres > 0 ~ "Gap 3"))

plot(kern_conservation_GAP["gap"])


```

```{r}
#explore soil quality in the conservation area

```


```{r}
# #map it
# tmap_mode("view")
# 
# tm_shape(conservation_areas) +
#   tm_polygons("unit_name", legend.show = FALSE)
```