---
title: "Finding Fallow Fields"
author: "Iris Foxfoot"
date: "4/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(raster)
library(sf)
library(tidyverse)
library(janitor)
```

```{r}
#read in kernfields

#create list of years
kern_field_years <- c(2005:2020)

#loop through read-in process
for (i in kern_field_years) {
  filename <- paste0("kernfields_", i)
  wd <- paste0("data/kernfields/kern", i, ".shp")
  assign(filename, read_sf(wd))
}

#loop through listed sf objects and tidy
fields_cleaned_list <- lapply(mget(sprintf("kernfields_%d", 2005:2020)), 
                 function(x) 
                   {
                   
                   clean_names(x) %>%
                     st_make_valid() %>% 
                     st_transform(crs = "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs") %>%
                     #mutate(township = "T", range = "R") %>% 
                     dplyr::select(permit,
                                   pmt_site,
                                   township,
                                   range,
                                   s_status,
                                   p_status,
                                   dt_act)
                   
                     }
                 )


#rbind inputs
all_fields_binded <- do.call(rbind, fields_cleaned_list) %>% 
  st_make_valid()
```

```{r}
#read in kern county shapefile for clipping
kern_county <- read_sf("data/Kern_County_Boundary/Kern_County_Boundary.shp")
```

```{r}
#read in FAM data

#gather file data
my_files <- list.files("data/FAM_TIF", full.names = TRUE)

#this reads in the data as a raster stack
FAM_raster_stack <- raster::stack(my_files)

#save crs of FAM rasters
FAM_raster_stack_crs <- crs(FAM_raster_stack)

FAM_raster_stack_crs

#transform kern county SF object to be same as FAM rasters
kern_county_transformed <- kern_county %>% 
  st_transform(crs = FAM_raster_stack_crs)

st_crs(kern_county_transformed)

#reproject FAM raster
reproj_FAM <- projectRaster(FAM_raster_stack, crs = "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")

#crop and mask
FAM_raster_crop <- crop(FAM_raster_stack, extent(kern_county_transformed))
FAM_raster_mask <- mask(FAM_raster_crop, kern_county_transformed)

plot(FAM_raster_mask)

#polygonize masked FAM rasters
polylist = lapply(as.list(FAM_raster_mask), rasterToPolygons)
```

