---
title: "Difference Map"
author: "Iris Foxfoot"
date: "2/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(raster)
library(here)
library(sf)
library(tidyverse)
library(fasterize)
```

```{r}
#read in cropped wieslander data (previously cropped to kern county)
wieslander_data <- read_sf(here("data", "wieslander_clipped_kern.gpkg")) %>% 
  st_make_valid()

#get rid of whitespace problem  
wieslander_data$WHR1_TYPE <- str_trim(wieslander_data$WHR1_TYPE)


#read in backcast tif (previously cropped to kern county)
backcast_data <- raster(here("data", "modeled_1938.tif"))

```

```{r}
#view both
plot(backcast_data)

plot(st_geometry(wieslander_data))

#we can see they are in different projections, so we change one to another
backcast_data_reproj <- raster::projectRaster(backcast_data, crs = crs(wieslander_data))

proj_crs <- crs(wieslander_data)

#check crs to make sure transition worked
crs(backcast_data_reproj)
crs(wieslander_data)
```

### Part 1. Difference Map

```{r}
#now we create a binary crop/no crop raster by reclassifying the backcast data

#reclass df
reclass_df <- c(12.5, 13.5, 1,
              -Inf, 12.5, 0,
             13.5, Inf, 0)

#reclass matrix
reclass_m <- matrix(reclass_df,
                ncol = 3,
                byrow = TRUE)

#reclass raster
crop_raster_1938 <- reclassify(backcast_data_reproj, reclass_m)

#confirms we have only 0 and 1
hist(crop_raster_1938)

#looks about right
plot(crop_raster_1938)
```

```{r}
#now we have to do the same with the wieslander, with the extra step of converting to a raster

#first step is to make an extra raster to "write" the rasterized wieslander data to
raster_template <- backcast_data_reproj

#then we create a new col with bindary crop info in the wieslander shapefile
wies_binary <- wieslander_data %>% 
  mutate(binary = case_when(WHR1_TYPE == "Cropland"~2, T ~ 0))

#now we rasterize
wies_raster <- fasterize::fasterize(wies_binary, raster_template, field = "binary")

#check with hist
hist(wies_raster)

#plot
plot(wies_raster)
```

```{r}
#now we just stack the two and add
rasters_overlayed<- overlay(crop_raster_1938, wies_raster, fun=sum)

pal <- colorRampPalette(c("gray", "blue","yellow", "purple"))

#plot
plot(rasters_overlayed,
     main = "cropland difference map",
     col = pal(4),
    legend = F)
legend("topright", 
       legend = c("No Crops", "Backcast Crops", "Wies Crops", "Both Layer Crops"), 
       fill = pal(4))
```
### Part 2. Shrubs and Grassland Analysis

```{r}
#convert backcast raster to polygon
backcast_poly <- rasterToPolygons(backcast_data_reproj, fun=NULL, n=4, na.rm=TRUE, digits=12, dissolve=FALSE)

#convert to sf object
backcast_sf <- st_as_sf(backcast_poly)

#filter for shrubland and grassland
shrub <- backcast_sf %>% 
  filter(modeled_1938 == 12)

grass <- backcast_sf %>% 
  filter(modeled_1938 == 11)

#crop wieslander veg layer to backcast shrub or grassland

#shrub
shrub_wies_values <- st_intersection(wieslander_data, shrub)

plot(st_geometry(shrub_wies_values))

#grass
grass_wies_values <- st_intersection(wieslander_data, grass)

plot(st_geometry(shrub_wies_values))

#make histograms

#shrub
shrub_veg_types <- shrub_wies_values %>% 
  group_by(WHR1_TYPE) %>% 
  summarise(area = sum(AREA_HA))
  
ggplot(data = shrub_veg_types) +
  geom_col(aes(y = reorder(WHR1_TYPE, area), x = area)) +
  labs(x = "Area (Hectares)", y = "Veg Type",
       title = "Weislander vegetation for backcast shrubland") +
  theme_minimal() +
  theme(text = element_text(size=10))

#grass
grass_veg_types <- grass_wies_values %>% 
  group_by(WHR1_TYPE) %>% 
  summarise(area = sum(AREA_HA))
  
ggplot(data = grass_veg_types) +
  geom_col(aes(y = reorder(WHR1_TYPE, area), x = area)) +
  labs(x = "Area (Hectares)", y = "Veg Type",
       title = "Weislander vegetation for backcast grassland") +
  theme_minimal() +
  theme(text = element_text(size=10))
```

### Part 3. What was converted to crops?

```{r, cache=TRUE}
#turn off scientific notation for viz
options(scipen = 100)

#read in unioned field file (made in previous workflow)
present_day_fields <- read_sf(here("data", "shapefiles_written", "unioned_fields_20162019", "unioned_fields_20162019.shp")) %>% 
  st_transform(., proj_crs) %>% 
  st_make_valid()

#crop weis veg values to present day crops
veg_before_crops <- st_intersection(wieslander_data, present_day_fields)

#plot to check it worked
plot(st_geometry(veg_before_crops))

#group by veg type and sum area
grouped_veg <- veg_before_crops %>% 
  group_by(WHR1_TYPE) %>% 
  summarise(area_ha = sum(AREA_HA))


#plot it
ggplot(data = grouped_veg) +
  geom_col(aes(y = reorder(WHR1_TYPE, area_ha), x = area_ha)) +
  labs(x = "Area (Hectares)", y = "Veg Type",
       title = "Vegetation types of present-day fields") +
  theme_minimal() +
  theme(text = element_text(size=10))
```

