---
title: "Kern County Fields Through Time"
author: "Iris Foxfoot"
date: "1/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

```{r get_packages}
knitr::opts_chunk$set(echo = TRUE)
library(sf) #for polygons
library(tidyverse) #for data wrangling
library(here) #for file paths
library(raster) #for rasters
library(fasterize) #for making rasters
library(tmap) #for interactive maps
library(janitor) #for cleaning names
library(stampr) #for space time analysis
library(sp) #spatial polygons, required for stampr to work
library(smoothr) #drops slivers
library(nngeo) #for removing geometry holes
```

# Introduction

# Read in field data and wrangle it

In this section we read in the field data and wrangle it such that the end product is a single dataframe containing shapefiles for fields in all years. We also need to add a unique ID column and a year column. 

```{r field_data_wrangling}
#read in kern data
#must have the following file path in working directory: data/kernfields/kernYEAR.shp

#create list of years
kern_field_years <- c(2005:2021)

#loop through read-in process
for (i in kern_field_years) {
  filename <- paste0("kernfields_", i)
  wd <- paste0("data/kernfields/kern", i, ".shp")
  assign(filename, read_sf(wd))
}

#loop through listed sf objects and tidy
fields_cleaned_list <- lapply(mget(sprintf("kernfields_%d", 2005:2021)), 
                 function(x) 
                   {
                   
                   clean_names(x) %>%
                     st_make_valid() %>% 
                     st_transform(crs = "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs") %>%
                     dplyr::select(permit,
                                   #permittee,
                                   pmt_site,
                                   #comm,
                                   s_status,
                                   p_status,
                                   #acres,
                                   dt_act)
                   
                     }
                 )


#rbind inputs
all_fields_binded <- do.call(rbind, fields_cleaned_list) %>% 
  st_make_valid()

#make id column, get year
all_fields <- all_fields_binded%>% 
  st_make_valid() %>% 
  rownames_to_column(var="ID") %>% 
  mutate(year = lubridate::year(dt_act)) %>% 
  dplyr::select(-dt_act) %>% 
  mutate(pmt_site_year = str_c(year, "_", pmt_site))

#make group ID based on geometry. About half of geometry is redundant
all_fields_grouped <- all_fields %>% 
  mutate(group = match(geometry, unique(geometry)))

#aggregate based on group
all_feilds_comb <- st_combine(all_fields_grouped)

#will need to merge site ID to geometeries

#will need to write it to shapefile
#st_write(all_feilds_agg, here("data", "shapefiles_written", "fields_gr_by_geom.shp"), driver = "ESRI Shapefile")
```

# building a small example

```{r}
#select region (based off of farmer)
kern_subset <- kernfields_2019 %>% 
  filter(AGENT == "McMANUS/WILSON,MICHELE/AARIN")

#crop several other years
kern_19_crop <- st_crop(kernfields_2019, kern_subset)

kern_18_crop <- st_crop(kernfields_2018, kern_subset)

kern_17_crop <- st_crop(kernfields_2018, kern_subset)

#bind together
sample_bind <- rbind(kern_17_crop, kern_18_crop, kern_19_crop) %>% 
  st_make_valid() %>% 
  clean_names() %>%
  mutate(year = lubridate::year(dt_act))

#clean up columns  
sample_clean <- sample_bind %>% 
  mutate(pmt_site_year = str_c(year, "_", pmt_site)) %>% 
  dplyr::select(pmt_site_year)

#combine geometries
sample_comb <- sample_clean %>%
  summarise(geometry = st_combine(geometry)) %>%
  st_cast("POLYGON")

#add ID data back to geometry
sample_join <- st_join(sample_comb, sample_clean) %>% 
  distinct() %>% 
  st_make_valid()

#creating pivot table
sample_pivot <- sample_join %>% 
  separate(pmt_site_year, into = c("year", "pmt_site"), sep = "_") %>% 
  pivot_wider(names_from = year, values_from = pmt_site) %>% 
  st_as_sf() %>% 
  mutate(id = row_number())
```

```{r}
plot(st_geometry(kern_17_crop))
plot(st_geometry(kern_18_crop))
plot(st_geometry(kern_19_crop))
plot(st_geometry(sample_pivot))
```

```{r}
tmap_mode("view")
tm_shape(sample_pivot) +
  tm_polygons(id = "pmt_site")
```

```{r}
tmap_mode("view")
tm_shape(sample_bind) +
  tm_polygons(id = "pmt_site")+
  tm_facets(sync = TRUE, by = "year")
  
```
