---
title: "Storie Index Values and PermitSite ID"
author: "Iris Foxfoot"
date: "3/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf) #for polygons
library(tidyverse) #for data wrangling
library(here) #for file paths
library(raster) #for rasters
library(fasterize) #for making rasters
library(janitor) #for cleaning names
```

# Read in Soil data and Rasterize It

In this code chunk we read in soil data created previously in 3.0_SSURGOStorieInd_copy.rmd and rasterize various components.

```{r}
#read in SSURGO data
soil_sf <- read_sf(here("R_input", "spatial", "SSURGOsoil", "kern_soil.gpkg")) %>% 
  st_transform(crs = "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")


#write function to change categorical cols into numeric for rasterization
class_cols <- function(colname) {
  case_when(
      str_detect(colname, "Grade 1") ~ 1,
      str_detect(colname, "Grade 2") ~ 2,
      str_detect(colname, "Grade 3") ~ 3,
      str_detect(colname, "Grade 4") ~ 4,
      str_detect(colname, "Grade 5") ~ 5,
      str_detect(colname, "Grade 6") ~ 6
  )
}

#reclassign categorical variables
soil_sf_classed <- soil_sf %>% 
  mutate(interpllc_classed = class_cols(interpllc)) %>% 
  mutate(interplrc_classed = class_cols(interplrc)) %>% 
  mutate(interphrc_classed = class_cols(interphrc)) %>% 
  mutate(interphhc_classed = class_cols(interphhc))


# Initialize empty raster
ras = raster()

# Set the raster extent based on the soil shapefile
extent(ras) = extent(soil_sf)

# Set raster resolution (meters)
res(ras) = 60

#rasterize (each raster contains one storie index measure)

#continuous values
interpl = fasterize(soil_sf, ras, field = "interpl")
interplRV = fasterize(soil_sf, ras, field = "interplRV")
interphr = fasterize(soil_sf, ras, field = "interphr")
interphh = fasterize(soil_sf, ras, field = "interphh")

#classed values
interpllc = fasterize(soil_sf_classed, ras, field = "interpllc_classed")
interplrc = fasterize(soil_sf_classed, ras, field = "interplrc_classed")
interphrc = fasterize(soil_sf_classed, ras, field = "interphrc_classed")
interphhc = fasterize(soil_sf_classed, ras, field = "interphhc_classed")

#create list of all rasters
rasters <- c(interpl, interplRV, interphr, interphh, interpllc, interplrc, interphrc, interphhc)

#create raster stack
soil_ras <- stack(rasters)

soil_ras_test <- c(interpllc, interpl) %>% 
  stack()

# Define the CRS again
crs(soil_ras) = "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"

crs_raster <- crs(soil_ras)

```

# Read in and process field data

```{r}
#read in kern field data
#must have the following file path in working directory: data/kernfields/kernYEAR.shp

#create list of years
kern_field_years <- c(2005:2019)

#loop through read-in process
for (i in kern_field_years) {
  filename <- paste0("kernfields_", i)
  wd <- paste0("data/kernfields/kern", i, ".shp")
  assign(filename, read_sf(wd))
}

#loop through listed sf objects and tidy
fields_cleaned_list <- lapply(mget(sprintf("kernfields_%d", 2005:2019)), 
                 function(x) 
                   {
                   
                   clean_names(x) %>%
                     st_make_valid() %>% 
                     st_transform(crs = "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs") %>% 
                     dplyr::select(permit,
                                   permittee,
                                   pmt_site,
                                   comm,
                                   s_status,
                                   p_status,
                                   acres,
                                   dt_act)
                   
                     }
                 )


#rbind inputs
all_fields_binded <- do.call(rbind, fields_cleaned_list) %>% 
  st_make_valid()

#make id column, get year
all_fields <- all_fields_binded%>% 
  st_make_valid() %>% 
  rownames_to_column(var="ID") %>% 
  mutate(year = lubridate::year(dt_act)) %>% 
  dplyr::select(-dt_act) %>% 
  st_transform(crs = crs_raster)


#recast as multipolygon
all_fields <- st_cast(all_fields, "MULTIPOLYGON")

st_is_valid(all_fields, reason = T)

#convert to spatial
all_fields_sp <- as(all_fields, "Spatial")
```

# Extract average Storie Index values per permitsiteID

```{r}
#extract storie index value per each year
all_fields_soil <- raster::extract(soil_ras, #Storie Index Raster Stack
                           all_fields, #Extract based on Kern Ag polygon outlines
                           fun = mean, #Find the mean value of raster cells that overlap with each polygon
                           small = TRUE, #Include mean values for small polygons
                           weights = TRUE, #Add weights for weighted means
                           normalizeWeights = TRUE,
                           na.rm = TRUE, #Ignore NAs when calculating mean values BUT then need to change 0s back to NAs
                           df = TRUE #save as a df
                           )


#change '0' values to NA
all_fields_soil[all_fields_soil == 0] <- NA

#how many NAs in each column?
colSums(is.na(all_fields_soil))

#replace names
names(all_fields_soil) <- c("ID", "interpl", "interplRV", "interphr", "interphh", "interpllc", "interplrc", "interphrc", "interphhc")

#bind to ag shapefile
fields_storie <- cbind(all_fields, all_fields_soil)

#write to csv
write.csv(fields_storie, here("data", "shapefiles_written", "fields_with_storie_indexes_05MAR22.csv"), row.names = FALSE)
```


